P2P
extreal-dev/Extreal.Integration.P2P.WebRTC pull request #1
Opened 2023-07-27 16:48 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [x] 全ての自動テストが成功することを確認しました
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [x] GuideのReleaseページに変更内容が追加されることを確認しました
- [x] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [x] GuideのLearningページに変更が反映されることを確認しました
- [x] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-08-18 11:32 UTC, sus-taguchi-t requested changes

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/Host.cs
> +        public string Id { get; private set; }
セッターは不要です。
`Name` も同様です。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/NativeClientState.cs
> +        private readonly BoolReactiveProperty isOfferAnswerProcessFinished = new BoolReactiveProperty(false);
変数として値を保持しておく必要がないのであれば `Subject<bool>` が良いと思います。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/NativeClientState.cs
> +        internal void FinishIceCandidateGathering() => isIceCandidateGatheringFinished.Value =true;
`=true` のフォーマットが崩れていると静的解析が警告を出しています。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +                switch (pc.IceConnectionState)
「欠落しているケースがある」という `IDE0010` 番の静的解析が警告を発していました。
`case RTCIceConnectionState.Max:` というケースが落ちているようです。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +                clientState.FinishOfferAnswerProcess();
Offer や Answer で情報をやり取りすることを Negotiation というらしいので `FinishNegotiation()` の方がすっきりすると思いますがいかがでしょうか？
単語の分かりやすさ重視ならばこのままの名称でも良いと思います。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +        public string HostId { get; private set; }
これら 2 つのプロパティは `public` ですが、C# ドキュメントは書かないで大丈夫でしょうか？
`AddPcCreateHook` および `AddPcCloseHook` も同様です。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        protected CompositeDisposable Disposables { get; private set; } = new CompositeDisposable();
`private set;` は不要です。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        /// <exception cref="HostNameAlreadyExistsException">when hostname already exists at creation of host.</exception>
when -> When

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/PeerConfig.cs
> +        public string SignalingUrl { get; private set; }
`private set;` は不要です。
他のプロパティも同様です。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +#pragma warning restore CS1998
以下の書き方の方がすっきりすると思いますがいかがでしょうか？
`DoStopAsync` も同様です。

```csharp
#pragma warning disable CS1998
        protected override async UniTask DoStartClientAsync(string hostId)
            => WebGLHelper.CallAction(WithPrefix(nameof(DoStartClientAsync)), hostId);
#pragma warning restore CS1998
```

2023-08-18 11:32 UTC, sus-taguchi-t commented on Samples~/MVS/App/StageConfig.cs
> +        menuName = "Web.Common/" + nameof(StageConfig),
WebCommon/ ->  P2P.WebRTC/

2023-08-18 11:32 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
こちらと同様にディレクトリ名の末尾に `~` を付けた方が良いと思いました。
https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1#discussion_r1296903831

2023-08-18 11:32 UTC, sus-taguchi-t commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
CreateHostRespone -> CreateHostResponse

2023-08-18 11:32 UTC, sus-taguchi-t commented on WebScripts~/src/PeerClient.ts
> +        await this.handlePcAsync("sendOffer", to, async (pc: RTCPeerConnection) => {
sendOffer -> sendOfferAsync

2023-08-18 11:32 UTC, sus-taguchi-t commented on Samples~/MVS/Extreal.Integration.P2P.WebRTC.MVS.asmdef
> +        "Unity.Collections",
`Unity.Collections` は不要です。

2023-08-18 11:32 UTC, sus-taguchi-t commented on Runtime/Extreal.Integration.P2P.WebRTC.asmdef
> +        "Unity.Collections",
`Unity.Collections` は不要です。

2023-08-29 05:59 UTC, sasuke9410 commented on Runtime/Host.cs
> +        public string Id { get; private set; }
Fixed 83b80cbe03d270e94a6389a72720da915913f39e

2023-08-29 07:28 UTC, sasuke9410 commented on Runtime/NativeClientState.cs
> +        private readonly BoolReactiveProperty isOfferAnswerProcessFinished = new BoolReactiveProperty(false);
Fixed fd1834b11c4f3998d1c6b3ca6dbe96d57faa7fd6

2023-08-29 07:31 UTC, sasuke9410 commented on Runtime/NativeClientState.cs
> +        internal void FinishIceCandidateGathering() => isIceCandidateGatheringFinished.Value =true;
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/1#discussion_r1297071713
上記指摘対応で該当項目が削除されたため解決

2023-08-29 08:10 UTC, sasuke9410 commented on Runtime/NativePeerClient.cs
> +                switch (pc.IceConnectionState)
UnityのWebRTCライブラリのリファレンスを読みましたが、RTCIceConnectionState.Maxに関しての記述はありませんでした。
https://docs.unity3d.com/ja/Packages/com.unity.webrtc@2.1/api/Unity.WebRTC.RTCIceConnectionState.html

おそらく上限値に達した状態を指していると思いますが、上限値に達しても特別な処理は行わない認識です。

Fixed 7797d281bf385b0a7e030e55427105b67cfce91c

2023-08-29 08:31 UTC, sasuke9410 commented on Runtime/NativePeerClient.cs
> +                clientState.FinishOfferAnswerProcess();
強いこだわりはありませんが、
offer/answerモデルと説明しているサイトも多かったので、
分かりやすさ重視でこのままでいいと考えています。

2023-08-29 08:55 UTC, sasuke9410 commented on Runtime/PeerClient.cs
> +        protected CompositeDisposable Disposables { get; private set; } = new CompositeDisposable();
Fixed 48e8a50081306fd413a94aabc479eb3a4ea6254a

2023-08-29 08:57 UTC, sasuke9410 commented on Runtime/PeerClient.cs
> +        /// <exception cref="HostNameAlreadyExistsException">when hostname already exists at creation of host.</exception>
Fixed 1de3481ecd0ee5c85466ca703f883695a80bde11

2023-08-29 08:59 UTC, sasuke9410 commented on Runtime/PeerConfig.cs
> +        public string SignalingUrl { get; private set; }
Fixed bca0c5efb299f58b3a1c9f37f1374dabdc061d58

2023-08-29 09:11 UTC, sasuke9410 commented on Samples~/MVS/App/StageConfig.cs
> +        menuName = "Web.Common/" + nameof(StageConfig),
Fixed 1c92692f752a95051d4cd66050c319d67f8a301d

2023-08-29 09:54 UTC, sasuke9410 commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
Fixed f514ea12057abd6d10728126ff63108b9626ea70

2023-08-29 09:57 UTC, sasuke9410 commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
Fixed b05e5082d2d8939877b21dc4eac73ef40c27f113

2023-08-29 09:59 UTC, sasuke9410 commented on WebScripts~/src/PeerClient.ts
> +        await this.handlePcAsync("sendOffer", to, async (pc: RTCPeerConnection) => {
Fixed 1b068ecc058ddcb81c3118eddf84e0213294d26d

2023-08-29 10:11 UTC, sasuke9410 commented on Samples~/MVS/Extreal.Integration.P2P.WebRTC.MVS.asmdef
> +        "Unity.Collections",
Fixed 60c2c23effc0ba0a5302eb438bf7b62da0a6891e

2023-08-29 10:11 UTC, sasuke9410 commented on Runtime/Extreal.Integration.P2P.WebRTC.asmdef
> +        "Unity.Collections",
Fixed 60c2c23effc0ba0a5302eb438bf7b62da0a6891e

2023-08-30 01:43 UTC, sasuke9410 commented on Runtime/NativePeerClient.cs
> +        public string HostId { get; private set; }
追記しました。
Fixed 6b0188f806ec1917618dc2e3485831384a69cc0c

2023-08-30 01:44 UTC, sasuke9410 commented on Runtime/WebGLPeerClient.cs
> +#pragma warning restore CS1998
Fixed fa12e8a1a44d97c1b176c0e2982666fc4e834683

2023-08-31 02:48 UTC, sus-taguchi-t commented on Runtime/Host.cs
> +        public string Id { get; private set; }
確認しました！

2023-08-31 02:50 UTC, sus-taguchi-t commented on Runtime/NativeClientState.cs
> +        private readonly BoolReactiveProperty isOfferAnswerProcessFinished = new BoolReactiveProperty(false);
`NativeClientState` の `Cliear` メソッドは必要かと思ったのですが、削除した状態でも想定通りな動きになっていますでしょうか？

2023-08-31 02:50 UTC, sus-taguchi-t commented on Runtime/NativeClientState.cs
> +        internal void FinishIceCandidateGathering() => isIceCandidateGatheringFinished.Value =true;
確認しました！

2023-08-31 02:51 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +                switch (pc.IceConnectionState)
ありがとうございます！
確認しました！

2023-08-31 02:52 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +                clientState.FinishOfferAnswerProcess();
分かりました。

2023-08-31 02:56 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +        public string HostId { get; private set; }
`AddPcCreateHook` と `AddPcCloseHook` に関してはもう少し本質的な説明の方が良くないでしょうか？
「Peer connection 作成時に呼ばれる処理を追加します」など。

2023-08-31 02:56 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        protected CompositeDisposable Disposables { get; private set; } = new CompositeDisposable();
確認しました！

2023-08-31 02:57 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        /// <exception cref="HostNameAlreadyExistsException">when hostname already exists at creation of host.</exception>
確認しました！

2023-08-31 02:57 UTC, sus-taguchi-t commented on Runtime/PeerConfig.cs
> +        public string SignalingUrl { get; private set; }
確認しました！

2023-08-31 02:59 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +#pragma warning restore CS1998
`DoStopAsync` は変更しないのでしょうか？

2023-08-31 02:59 UTC, sus-taguchi-t commented on Samples~/MVS/App/StageConfig.cs
> +        menuName = "Web.Common/" + nameof(StageConfig),
DoStopAsync

2023-08-31 02:59 UTC, sus-taguchi-t commented on Samples~/MVS/App/StageConfig.cs
> +        menuName = "Web.Common/" + nameof(StageConfig),
確認しました！

2023-08-31 06:24 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
確認しました！

2023-08-31 06:24 UTC, sus-taguchi-t commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
確認しました！

2023-08-31 06:27 UTC, sus-taguchi-t commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
ここを修正した結果 `CreateHostRespone` を使用していた箇所がエラーを発しているので修正をお願いします。

2023-08-31 06:28 UTC, sus-taguchi-t commented on WebScripts~/src/PeerClient.ts
> +        await this.handlePcAsync("sendOffer", to, async (pc: RTCPeerConnection) => {
確認しました！

2023-08-31 06:28 UTC, sus-taguchi-t commented on Samples~/MVS/Extreal.Integration.P2P.WebRTC.MVS.asmdef
> +        "Unity.Collections",
確認しました！

2023-08-31 06:28 UTC, sus-taguchi-t commented on Runtime/Extreal.Integration.P2P.WebRTC.asmdef
> +        "Unity.Collections",
確認しました！

2023-08-31 06:31 UTC, sus-taguchi-t requested changes

2023-08-31 06:31 UTC, sus-taguchi-t commented on SignalingServer~/README.md.meta
後からの指摘ですみません。
`SignalingServer~` ディレクトリ以下のメタファイルもすべて削除した方が良いと思います。

2023-09-08 05:26 UTC, sasuke9410 commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
すみません 見落としてました
Fixed 30a77f1a0b820b8a846137bf61380247ad0a98f4

2023-09-08 06:48 UTC, sasuke9410 commented on Runtime/NativePeerClient.cs
> +        public string HostId { get; private set; }
summaryコメントに悩んでいたので助かりました。
ありがとうございます。
Fixed fe838190bb4556a5c4ad1447f38d206642ab71ff

2023-09-08 08:57 UTC, sasuke9410 commented on SignalingServer~/README.md.meta
Fixed a24d3b31fe6233d59b154caf10c4725520af29ab

2023-09-08 09:39 UTC, sasuke9410 commented on Runtime/NativeClientState.cs
> +        private readonly BoolReactiveProperty isOfferAnswerProcessFinished = new BoolReactiveProperty(false);
削除した状態でも、問題なく動作しました。
しかし、CombineLatestが過去の状態を保持することを考えると、falseで初期化しておく方が安全だと判断したため
Clear関数を再追加しました。

Fixed 78b7017b2fa4eb58cba91abad6e5cf51e205d7b8

2023-09-08 09:53 UTC, sasuke9410 commented on Runtime/WebGLPeerClient.cs
> +#pragma warning restore CS1998
すみません 対応漏れでした。
Fixed cd94e13b97e3ab2e4d5f1f490c0cb76b32f1529a

2023-09-11 04:26 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +        public string HostId { get; private set; }
確認しました。

2023-09-11 04:28 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +#pragma warning restore CS1998
確認しました。

2023-09-11 06:53 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +        protected override async UniTask DoStartClientAsync(string hostId)
このメソッドの宣言の方で `CS1998` の静的解析が警告を出していると思うので、抑制してほしいです。
`DoStopAsync` の方も同様です。

2023-09-11 06:53 UTC, sus-taguchi-t commented on SignalingServer~/index.ts
> +type CreateHostRespone = {
確認しました。

2023-09-11 07:05 UTC, sus-taguchi-t requested changes, later dismissed

2023-09-11 07:05 UTC, sus-taguchi-t commented on .gitignore
> +Samples~/MVS/WebGLScripts/node_modules*
`WebGLScripts` の末尾に `~` が入っていません。

2023-09-11 07:05 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +        protected override async UniTask DoStartClientAsync(string hostId)
このメソッドの宣言の方で `CS1998` の静的解析が警告を出していると思うので、抑制してほしいです。
`DoStopAsync` の方も同様です。

2023-09-11 07:05 UTC, sus-taguchi-t commented on SignalingServer~/README.md.meta
確認しました。

2023-09-12 04:37 UTC, sasuke9410 commented on .gitignore
> +Samples~/MVS/WebGLScripts/node_modules*
Fixed d35aa342deeb6523c22bd7ff4fe1aefd16ebbab6

2023-09-12 04:50 UTC, sasuke9410 commented on Runtime/WebGLPeerClient.cs
> +        protected override async UniTask DoStartClientAsync(string hostId)
FIxed 1200eb6881f4e616a4aef702142877789833dcb9

2023-09-13 07:02 UTC, sasuke9410 commented on README.md
> +- Enter the following command in the `MVS/WebGLScripts~` directory.
サンプルのimport後、MVS直下のビルド対象ディレクトリは
WebScriptsではなく、
Assets\Samples\Extreal.Integration.P2P.WebRTC\1.0.0-next.4\MVS\WebGLScripts~
であるため修正しました。

2023-09-13 07:06 UTC, sasuke9410 commented on README.md
> +  - Two clients can join a group (multiple client join)
Extreal.Guideに載っている、call meの送信/受信を確認するために必要な
ClientsAlreadyJoined(参加済クライアント)を使ったケースが存在しないため追記しました。
https://extreal-dev.github.io/Extreal.Guide/next/integration/p2p.webrtc/

2023-09-14 08:37 UTC, mahaweilu commented on Runtime/WebGLPeerClient.cs
> +        protected override async UniTask DoStartClientAsync(string hostId)
fixed https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/1/commits/e6ca5d305a75e46f04c8b4142bf13771f3dafd6e

2023-09-14 08:38 UTC, kiyohome commented on Runtime/WebGLPeerClient.cs
> +        protected override async UniTask DoStartClientAsync(string hostId)
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/1/commits/e6ca5d305a75e46f04c8b4142bf13771f3dafd6e

2023-09-14 08:39 UTC, mahaweilu approved these changes

2023-09-14 08:40 UTC, merged