自身のClientIDを取得できるように修正
extreal-dev/Extreal.Integration.P2P.WebRTC pull request #10
Opened 2023-12-13 10:18 UTC by sasuke9410

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-20 06:45 UTC, mahaweilu commented
> * C#側のコードで、即時で切断するメソッドを呼んでいなかったのを修正しました
> * WebGL側での非同期処理のHookの動作がエラーハンドリングの修正時に変わってしまっていたため修正しました
> * サンプルでエラーハンドリング周りの処理を確認する部分が一部抜けていたため、サンプルを修正しました

> # レビュアーへのメッセージ

この3つの説明が読むだけで分からなったので修正お願いしたいです。主に以下の観点です。
- ピンポイントとなる修正箇所を[こちら](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8#issue-2010945354)のPR説明の1行目と同じようにcommitリンクを添付してもよさそうです
- 現状developの違い
  -  例えば、「即時で切断するメソッドを呼んでいなかった」で何の事象が発生するかです

2023-12-20 06:54 UTC, sus-taguchi-t requested changes

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +    ```
これではどういうテストケースがあるのか分からないので、テストケースごとに記述した方が良いと思います。
クライアント切断時やクライアント側のテストケースも同様です。

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +  - When clients disconnect, the socket ID of each connected client is displayed
each connected client -> each disconnected client

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +  - When a client connects, the socket ID of the client is displayed
When a client connects, the socket ID of the client is displayed
->  When other clients connect, their socket IDs is displayed

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +  - When a client disconnects, the socket ID of the client is displayed
これは自分についてのテストケースでしょうか？それとも他のクライアントについてでしょうか？

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +  - Logs are output to the console in the following order when another client join
when another client join -> when other clients join

2023-12-20 06:54 UTC, sus-taguchi-t commented on README.md
> +  - Logs are output to the console in the following order when other client leave
when other client leave -> when other clients leave

2023-12-20 06:54 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        /// <value>Socket id</value>
使用者から見えないプロパティなので C# ドキュメントは不要だと思います。
他のメンバについても同様です。

2023-12-20 06:54 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        protected abstract string GetSocketId();
このメソッドを使用している場所の近くに定義してあげた方が見やすくないでしょうか？

2023-12-20 06:54 UTC, sus-taguchi-t commented on Samples~/MVS/ClientControl/ClientControlPresenter.cs
> +                    appState.Notify($"Received: {nameof(PeerClient.OnStarted)}\nMy ID: {id}");
改行コードは `System.Environment.NewLine` を使用した方が良くないでしょうか？
他の場所でも同様です。

2023-12-20 06:54 UTC, sus-taguchi-t commented on Samples~/MVS/App/AppState.cs
> +        private readonly ReactiveProperty<string> socketId = new ReactiveProperty<string>();
保持したソケット ID を使用していないのに ReactiveProperty を使用しているのには違和感があります。
Subject ではいけないでしょうか？

2023-12-20 06:54 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/DummyClient.ts
> +    getPeerClient().addPcCreateHook(DummyClient.createPcAsync)
非同期メソッドを close に登録するテストケースはなくて良いのでしょうか？

2023-12-20 07:04 UTC, mahaweilu commented on Runtime/NativePeerClient.cs
> +            await socket.DisconnectAsync();
ここをawait socket.DisconnectAsync();を呼ばずに何が起きるんですか？また、awaitではなく、socket.DisconnectAsync();でどう違いますか？

2023-12-20 07:04 UTC, mahaweilu commented on WebScripts~/src/PeerClient.ts
> -           await this.handleHook(() => hook(id, isOffer, pc));
developブランチで不具合（https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/9/)
　のマージによる）があり、この修正がされたと思いますが、PR説明で[コメントした](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10#issuecomment-1863937368)ように経緯が分かるような説明があった方が良いと思います。

2023-12-20 07:04 UTC, mahaweilu commented on Runtime/PeerClient.cs
> +        /// Invokes immediately after another user connects.
remote user/clientはどうですか？もし既存のdocsにanother userなどを使っていれば、そのままでも大丈夫です。

公式に[Connecting to a remote peer](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation#connecting_to_a_remote_peer)の表現があるので提案しました。

2023-12-20 07:04 UTC, mahaweilu commented on README.md
> +    Error: CreatePeerClient Error Test
指摘ではなく、コメントだけですが。DummyClient.tsの作成でエラーハンドリングのテストを行うのが良いテストだと思いますが、打鍵テストで確認できなく、「 defensive implementation」のケースに当たる場合、
「// Not covered by testing due to defensive implementation」でもよいかと思いました。

他に同じようなエラーハンドリング実装は、テストはどうなっているかが気になっています。

2023-12-20 12:11 UTC, sasuke9410 commented on README.md
> +  - Logs are output to the console in the following order when client join
Whenから始まる文と、最後にWhenが付く両方のケースが混ざっているため、
どちらかに統一した方がいいと思います。
Clientのケースも同様です。

2023-12-21 06:16 UTC, sus-yoshikane-t commented on README.md
> +    ```
接続/切断時のHookのエラーハンドリング（2回エラーテストのログが出る）という形に修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/c6ba0e74847ad9bd1346c8915cf69bbac647ae67

```
- Error handling if an error occurs in hooks on connecting
    - Error test logs are displayed twice in console for each client connection
```
```
- Error handling if an error occurs in hooks on disconnecting
    - Error test logs are displayed twice in console for each client disconnect
```

2023-12-21 06:18 UTC, sus-yoshikane-t commented on README.md
> +  - When clients disconnect, the socket ID of each connected client is displayed
修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/commit/c6ba0e74847ad9bd1346c8915cf69bbac647ae67
```
  - The socket ID of each disconnected client is displayed when other clients disconnect
```

2023-12-21 06:19 UTC, sus-yoshikane-t commented on README.md
> +  - When a client connects, the socket ID of the client is displayed
修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/commit/c6ba0e74847ad9bd1346c8915cf69bbac647ae67
```
  - The socket ID of each connected client is displayed when other clients connect
```

2023-12-21 06:30 UTC, sus-yoshikane-t commented on README.md
> +  - Logs are output to the console in the following order when another client join
[こちらの修正](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10#discussion_r1433585473)で削除されました。

2023-12-21 06:30 UTC, sus-yoshikane-t commented on README.md
> +  - Logs are output to the console in the following order when other client leave
[こちらの修正](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10#discussion_r1433585473)で削除されました。

2023-12-21 06:32 UTC, sus-yoshikane-t commented on README.md
> +  - When a client disconnects, the socket ID of the client is displayed
他のクライアントが切断した際のテストケースです。
when other clients disconnectに修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/commit/c6ba0e74847ad9bd1346c8915cf69bbac647ae67
```
  - The socket ID of each disconnected client is displayed when other clients disconnect
```

2023-12-21 06:37 UTC, sus-yoshikane-t commented on Runtime/PeerClient.cs
> +        /// <value>Socket id</value>
削除しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/15cb5f28c230b0b822deebcd8d935efbc0e0db9d

2023-12-21 06:42 UTC, sus-yoshikane-t commented on Runtime/PeerClient.cs
> +        protected abstract string GetSocketId();
修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/b8a90ea04857fd581a315edb2fb238d62a59e091

2023-12-21 06:55 UTC, sus-yoshikane-t commented on Samples~/MVS/ClientControl/ClientControlPresenter.cs
> +                    appState.Notify($"Received: {nameof(PeerClient.OnStarted)}\nMy ID: {id}");
修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/c541848d04045e58d76b64d8c0ad88e45146d370

2023-12-21 06:55 UTC, sus-yoshikane-t commented on Samples~/MVS/App/AppState.cs
> +        private readonly ReactiveProperty<string> socketId = new ReactiveProperty<string>();
Subjectで問題ないため修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/07944461de16b99bc5500d252686f9c57b110ea0

2023-12-21 06:57 UTC, sus-yoshikane-t commented on Samples~/MVS/WebGLScripts~/src/DummyClient.ts
> +    getPeerClient().addPcCreateHook(DummyClient.createPcAsync)
addPcCloseHookでは非同期メソッドを受け付けていないため作成していません。

2023-12-21 07:04 UTC, sus-yoshikane-t commented on Runtime/NativePeerClient.cs
> +            await socket.DisconnectAsync();
socket.DisconnectAsync()を呼ばない場合、切断してから数秒間他のクライアント等からは接続し続けているように見えていました。socket.DisconnectAsync()を呼ぶことで、他のクライアント等からも即座に切断されます。WebGL側では同様のsocket.close()を呼んでいたため、socket.DisconnectAsync()を追加することでNativeでもWebGLでも即座に切断されるように揃えました。

次の行でsocket.Dispose()を実行する前にDisconnectAsyncの処理を完了させる意図でawaitしています。

2023-12-21 07:08 UTC, sus-yoshikane-t commented on WebScripts~/src/PeerClient.ts
> -           await this.handleHook(() => hook(id, isOffer, pc));
PRコメントを修正しました。
```
- [Hookのエラーハンドリングの修正時](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/9)にWebGL側で非同期処理のHookがawaitされない状態になっていたためawaitされるように修正しました
```

2023-12-21 07:09 UTC, sus-yoshikane-t commented on README.md
> +  - Logs are output to the console in the following order when client join
修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/c6ba0e74847ad9bd1346c8915cf69bbac647ae67

2023-12-21 07:20 UTC, sus-yoshikane-t commented on Runtime/PeerClient.cs
> +        /// Invokes immediately after another user connects.
他でanother userは使っていないため修正しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/2020cd4137e4af646bc836366a9cc1c9703084fb

2023-12-21 08:31 UTC, mahaweilu commented on Runtime/NativePeerClient.cs
> +            await socket.DisconnectAsync();
確認しました！ありがとうございます！

2023-12-21 08:36 UTC, mahaweilu commented on WebScripts~/src/PeerClient.ts
> -           await this.handleHook(() => hook(id, isOffer, pc));
確認しました。ありがとうございます！

2023-12-21 08:37 UTC, mahaweilu commented on Runtime/PeerClient.cs
> +        /// Invokes immediately after another user connects.
確認しました。ありがとうございます！

2023-12-21 10:31 UTC, sasuke9410 commented on README.md
> +  - Logs are output to the console in the following order when client join
確認しました！

2023-12-22 00:23 UTC, sus-taguchi-t commented on README.md
> +    ```
確認しました！

2023-12-22 00:24 UTC, sus-taguchi-t commented on README.md
> +  - When clients disconnect, the socket ID of each connected client is displayed
確認しました！

2023-12-22 00:24 UTC, sus-taguchi-t commented on README.md
> +  - When a client connects, the socket ID of the client is displayed
確認しました！

2023-12-22 00:25 UTC, sus-taguchi-t commented on README.md
> +  - When a client disconnects, the socket ID of the client is displayed
確認しました！

2023-12-22 00:25 UTC, sus-taguchi-t commented on README.md
> +  - Logs are output to the console in the following order when another client join
確認しました！

2023-12-22 00:25 UTC, sus-taguchi-t commented on README.md
> +  - Logs are output to the console in the following order when other client leave
確認しました！

2023-12-22 00:26 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        /// <value>Socket id</value>
確認しました！

2023-12-22 00:26 UTC, sus-taguchi-t commented on Runtime/PeerClient.cs
> +        protected abstract string GetSocketId();
確認しました！

2023-12-22 00:26 UTC, sus-taguchi-t commented on Samples~/MVS/ClientControl/ClientControlPresenter.cs
> +                    appState.Notify($"Received: {nameof(PeerClient.OnStarted)}\nMy ID: {id}");
確認しました！

2023-12-22 00:27 UTC, sus-taguchi-t commented on Samples~/MVS/App/AppState.cs
> +        private readonly ReactiveProperty<string> socketId = new ReactiveProperty<string>();
確認しました！

2023-12-22 01:05 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/DummyClient.ts
> +    getPeerClient().addPcCreateHook(DummyClient.createPcAsync)
すみません、私が把握していないので教えていただきたいのですが、
そのような仕様ってどこかに書いてありましたっけ？

2024-01-09 04:52 UTC, sus-yoshikane-t commented on Samples~/MVS/WebGLScripts~/src/DummyClient.ts
> +    getPeerClient().addPcCreateHook(DummyClient.createPcAsync)
現状記載はありません。
必要や要望に応じて、ガイドへの記載や他の部分でも非同期メソッドを受け付ける修正を行います。

2024-01-09 05:08 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/DummyClient.ts
> +    getPeerClient().addPcCreateHook(DummyClient.createPcAsync)
分かりました。

2024-01-09 05:10 UTC, sus-taguchi-t approved these changes

2024-01-10 02:43 UTC, kiyohome requested changes

2024-01-10 02:43 UTC, kiyohome commented on Runtime/NativePeerClient.cs
> +            FireOnUserConnected(id);
どうしてこのタイミングにしたんですか？

2024-01-10 02:43 UTC, kiyohome commented on Runtime/PeerClient.cs
> +                    Logger.LogDebug($"Socket id couldn't get.");
結局nullや空文字でもreturnするなら、この分岐とログ出力は何のために入れてますか？

2024-01-10 02:43 UTC, kiyohome commented on Runtime/PeerClient.cs
> +                    Logger.LogDebug($"Socket id couldn't get.");
あと、defensive implementationとありますが、どのあたりが防御的な実装ですか？
socketのidが取得できないタイミングで呼び出すことありますか？

2024-01-10 02:43 UTC, kiyohome commented on Runtime/WebGLPeerClient.cs
> +                ConnectionTimeout = (long)socketOptions.ConnectionTimeout.TotalMilliseconds,
このフォーマット、他のソースでもこうなってますか？

2024-01-10 02:43 UTC, kiyohome commented on WebScripts~/package.json
> +  "version": "1.0.2",
いきなり0->2になってるのは理由ありますか？
3桁目を挙げてる理由はありますか？
開発中はnext付けてませんでしたか？

2024-01-10 02:43 UTC, kiyohome commented on WebScripts~/src/PeerClient.ts
> +           await this.handleHook(hook, id, isOffer, pc);
こちらの変更理由はありますか？

2024-01-10 04:51 UTC, sus-yoshikane-t commented on Runtime/WebGLPeerClient.cs
> +                ConnectionTimeout = (long)socketOptions.ConnectionTimeout.TotalMilliseconds,
キャストは他のソースでも空白になっています。（以下のクエリ(?)でextreal-dev内を検索した範囲内です）
- `(C#基本型)`[検索](https://github.com/search?q=org%3Aextreal-dev+lang%3AC%23+%2F%5C%28%28bool%7Cbyte%7Csbyte%7Cchar%7Cdecimal%7Cdouble%7Cfloat%7Cint%7Cuint%7Cnint%7Cnuint%7Clong%7Culong%7Cshort%7Cushort%29%5C%29%2F&type=code)
  - `org:extreal-dev lang:C# /\((bool|byte|sbyte|char|decimal|double|float|int|uint|nint|nuint|long|ulong|short|ushort)\)/`
  - default(xxx)も混ざっています
- `(xxx)yyy` or `(xxx) yyy`[検索](https://github.com/search?q=org%3Aextreal-dev+lang%3AC%23+%2F%5C%28%5Cw%2B%3F%5C%29+%3F%28%5Cw%7C%5C%28%29%2F&type=code)
  - `org:extreal-dev lang:C# /\(\w+?\) ?(\w|\()/`
  - 1行のif文等も混ざっています

2024-01-10 05:12 UTC, sus-yoshikane-t commented on WebScripts~/src/PeerClient.ts
> +           await this.handleHook(hook, id, isOffer, pc);
アロー関数(ラムダ式)でhandleHookに渡してしまうと、hookが非同期関数だったかどうかを判定できず、handleHook内部で非同期関数がawaitされないため変更しました。

handleHook内部で非同期関数がawaitされない場合、Chat.WebRTCの非同期なcreatePcのhookでaddTrackのイベントが発火しないという問題が発生していました。

2024-01-10 05:23 UTC, sus-yoshikane-t commented on Runtime/PeerClient.cs
> +                    Logger.LogDebug($"Socket id couldn't get.");
当初publicプロパティにしていた際に通知のために入れていたものが残ってしまっていました。
privateに変更され、FireOnStarted()内でのみ使用しておりsocketのidが取得できないタイミングで呼び出すことはなく、プロパティである必要がなくなっていたため削除しました。https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/f8795fcc5bcdfadbd37e41a5ec801dd94a611f15

2024-01-10 07:22 UTC, sus-yoshikane-t commented on WebScripts~/package.json
> +  "version": "1.0.2",
Chat.WebRTCと並行して開発していた際に2回バージョンが変わったためです。
npm側はnextを付けていなかったのでそれに倣ってしまいました。（開発中のバージョンがインストールされてしまう可能性があると考えられるのでnextはつけるべきだと思います）
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/commit/63e03a45e7e79124112c5397b27961e4a6c47369

2024-01-10 07:31 UTC, sus-yoshikane-t commented on WebScripts~/package.json
> +  "version": "1.0.2",
そもそものところで申し訳ないのですが、リリース予定バージョンはGitHub側もnpm側も~メジャー~マイナーバージョンを上げた1.1.0という認識で良いでしょうか？

2024-01-10 08:38 UTC, sus-yoshikane-t commented on Runtime/NativePeerClient.cs
> +            FireOnUserConnected(id);
CreatePc時点で接続が確立していると勘違いしていました。
answerを受け取ってdoneを送る直前と、doneを受け取ったタイミングに修正しました。
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/13d8789ec24ef53ea50c3f747a33d17ba90ab5d8

2024-01-12 02:59 UTC, sus-yoshikane-t commented on WebScripts~/package.json
> +  "version": "1.0.2",
1.1.0-next.0に変更しました。npmへのアップロードと他モジュールの参照更新はまだ行っていません。
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/afeb538f304f8428481aae269661791be8c87e45

2024-01-16 11:52 UTC, kiyohome commented on Runtime/NativePeerClient.cs
> +            FireOnUserConnected(id);
接続が確立するタイミングは下記になるんですが、どうにかできそうでしょうか？
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/blob/develop/Runtime/PeerClient.cs#L21

2024-01-16 11:55 UTC, kiyohome commented on Runtime/WebGLPeerClient.cs
> +                ConnectionTimeout = (long)socketOptions.ConnectionTimeout.TotalMilliseconds,
今回の変更で空白が無くなってるので直した方がよくないでしょうか？

2024-01-16 11:57 UTC, kiyohome commented on WebScripts~/package.json
> +  "version": "1.0.2",
バージョニングはこちらを参照してください。
https://extreal-dev.github.io/Extreal.Guide/intro/#versioning

2024-01-16 11:58 UTC, kiyohome commented on WebScripts~/package.json
> +  "version": "1.0.2",
対応済みなので上記コメントを確認したらResolveをお願いします。

2024-01-16 12:00 UTC, kiyohome commented on WebScripts~/src/PeerClient.ts
> +           await this.handleHook(hook, id, isOffer, pc);
了解です！

2024-01-17 02:38 UTC, sus-yoshikane-t commented on WebScripts~/package.json
> +  "version": "1.0.2",
確認しました。

2024-01-17 02:43 UTC, sus-yoshikane-t commented on Runtime/WebGLPeerClient.cs
> +                ConnectionTimeout = (long)socketOptions.ConnectionTimeout.TotalMilliseconds,
記載が間違っており申し訳ありません。「キャストは他のソースでも空白"なし"になっています。」が正しかったです。

2024-01-18 00:26 UTC, sus-yoshikane-t commented on Runtime/NativePeerClient.cs
> +            FireOnUserConnected(id);
pc.OnConnectionStateChangeでConnectedが流れてきたタイミングで、各PeerConnectionの接続確立を検知できるようなので、pc.OnConnectionStateChangeを使用する方式で修正しました。
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/5b0a5d20264c3639a5c15fa6a91ccf8405785b5a

また、FireOnUserDisconnectedについては、ClosePc時にpc.ConnectionStateを見てConnectedだった場合に実行するように修正しました。
こちらについては先にClosePcが走るためか、pc.OnConnectionStateChangeにDisconnectedが流れてこなかったため、ClosePcで見るようにしました。

2024-01-23 06:49 UTC, sus-yoshikane-t commented on Runtime/NativePeerClient.cs
> +            FireOnUserConnected(id);
OnConnectionStateChange/ConnectionStateを使用しない形に修正しました。 https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/d0aabaf1a2cb90f1ffd2b19ab58346b39b9a912c

2024-01-23 07:55 UTC, kiyohome approved these changes

2024-01-24 09:49 UTC, merged