WebGLのスティッキーセッションへの対応
extreal-dev/Extreal.Integration.P2P.WebRTC pull request #13
Opened 2024-01-22 09:44 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

- WebGLでスティッキーセッションを使用するための設定をコンフィグで行えるように変更しました。
  - WebGLPeerConfigでwithCredentialsオプションを受け取れるように変更しました。
  - シグナリングサーバー側でスティッキーセッション有効時に使用する環境変数を追加しました。

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [x] 全ての自動テストが成功することを確認しました
  -  自動テストがないため未確認
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-01-29 01:54 UTC, sus-taguchi-t requested changes

2024-01-29 01:54 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +        public bool WithCredentials { get; set; }
このパラメータはどこで使用しているのでしょうか？

2024-02-21 04:23 UTC, sus-yoshikane-t commented on Runtime/WebGLPeerClient.cs
> +        public bool WithCredentials { get; set; }
最終的に下記の個所でSocket.IOのioクラスに渡されます。（渡される個所はそのまま利用可能だったため変化がありません）
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/blob/develop/WebScripts~/src/PeerClient.ts#L102

2024-02-21 05:38 UTC, kiyohome approved these changes

2024-02-26 01:49 UTC, sus-taguchi-t commented on Runtime/WebGLPeerClient.cs
> +        public bool WithCredentials { get; set; }
分かりました。ありがとうございます！

2024-02-26 01:49 UTC, sus-taguchi-t approved these changes

2024-02-26 01:49 UTC, merged