Fix p2 p
extreal-dev/Extreal.Integration.P2P.WebRTC pull request #2
Opened 2023-09-26 02:21 UTC by sasuke9410

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-09-26 02:28 UTC, kiyohome requested changes

2023-09-26 02:28 UTC, kiyohome commented on WebScripts~/src/PeerClient.ts
> +                    // do nothing
this.closePc(id);
をやめた理由はありますか？

2023-09-27 01:34 UTC, sasuke9410 commented on WebScripts~/src/PeerClient.ts
> +                    // do nothing
closePc処理を抜く必要が無いため、元に戻しました
c04fad3b74ccad701bcbe894deddbc5e454ebfa1

2023-09-29 09:25 UTC, kiyohome approved these changes

2023-09-29 09:26 UTC, merged