PeerConnectionのCreate/Closeでエラーが発生しても処理を継続するように変更
extreal-dev/Extreal.Integration.P2P.WebRTC pull request #9
Opened 2023-11-26 06:05 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-05 01:11 UTC, sus-taguchi-t requested changes

2023-12-05 01:11 UTC, sus-taguchi-t commented on WebScripts~/src/PeerClient.ts
> +                console.error(e);
こちらも C# と同じように `HandleHook` メソッドを作ってロジックの共通化をした方が良いと思うのですがいかがでしょうか？

2023-12-05 01:11 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
> +  version "1.0.0"
すみません、私が無知なので教えてほしいのですが、今のタイミングでメジャーバージョンを上げて良いものなのでしょうか？

2023-12-05 01:11 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
書く場所がないのでこちらで失礼します。
こちらテストするときのテストケースはどこかにありますでしょうか？

2023-12-07 01:25 UTC, sasuke9410 commented on WebScripts~/yarn.lock
> +  version "1.0.0"
自分も確証が持てなかったので伊藤さんに確認しました。
問題ないとのことでした。

2023-12-11 06:40 UTC, sasuke9410 commented on WebScripts~/src/PeerClient.ts
> +                console.error(e);
Fixed 18b3f71011c2d680a8f36f71050ba7589a143187

2023-12-11 06:47 UTC, sasuke9410 commented on WebScripts~/yarn.lock
Extreal.Integration.Chat.WebRTCではなく、
このリポジトリのサンプルで今回の修正箇所への確認が出来るよう修正しました。
テストケースは追加していませんが、
例外処理に入るクラスを呼び出しているため、これまで通りのテストでカバレッジ100%が確認出来ます。

2023-12-12 01:17 UTC, sus-taguchi-t commented on WebScripts~/src/PeerClient.ts
> +                console.error(e);
C# と同じような形にして引数を複数受け付ける形ではなく 1 つのAction（Function ?）を受け付ける形にはできないでしょうか？
その方がメンテナンスしやすくなると思います。

2023-12-12 01:17 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
> +  version "1.0.0"
分かりました。ありがとうございます！

2023-12-12 06:48 UTC, sus-taguchi-t requested changes

2023-12-12 06:48 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +            pcCreateHooks.ForEach(hook => HandleHook(nameof(CreatePc),() => hook.Invoke(id, isOffer, pc)));
静的解析が警告を発しています。

2023-12-12 06:48 UTC, sus-taguchi-t commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +            new NativeFailureClient(peerClient as NativePeerClient);
コンストラクタで作成したインスタンスを使用しないのは違和感があります。
ユーティリティクラスの静的メソッドにした方が良いと思います。

2023-12-12 06:48 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    this.getPeerClient = getPeerClient;
わざわざフィールドとして `peerClient` を保持する必要はないと思います。

2023-12-12 06:48 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/index.ts
> +addAction("failure", () => new FailureClient(peerAdapter.getPeerClient));
こちらも作成したインスタンスを使用しないのは同様に違和感があります。
普通の関数定義で良いのではないでしょうか？

2023-12-12 06:48 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
確認しました！

2023-12-13 04:45 UTC, sasuke9410 commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +            new NativeFailureClient(peerClient as NativePeerClient);
Fixed 9a51d0debd539af6bddac81656cb9434c1a24750

2023-12-13 06:59 UTC, sasuke9410 commented on Runtime/Host.cs
> +        public string Id { get; }
今回このcsファイルに修正は行っていませんが、
;の後に空白が無く静的解析でエラーが出ていたのでついでに修正しました。

2023-12-13 07:30 UTC, sasuke9410 commented on Runtime/NativePeerClient.cs
> +            pcCreateHooks.ForEach(hook => HandleHook(nameof(CreatePc),() => hook.Invoke(id, isOffer, pc)));
Fixed b5296ba91a39a6f91e73b6b40a4615e603ff7fe5

2023-12-13 07:31 UTC, sasuke9410 commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    this.getPeerClient = getPeerClient;
Fixed c627a15acd418cd74f0453afdcde675e655a2a10

2023-12-13 07:31 UTC, sasuke9410 commented on Samples~/MVS/WebGLScripts~/src/index.ts
> +addAction("failure", () => new FailureClient(peerAdapter.getPeerClient));
Fixed c627a15acd418cd74f0453afdcde675e655a2a10

2023-12-13 10:05 UTC, sasuke9410 commented on WebScripts~/src/PeerClient.ts
> +                console.error(e);
Fixed c4f2da0efb95a4effdf3587e68c0ce52fdc94d7a

2023-12-14 05:00 UTC, sus-taguchi-t commented on WebScripts~/src/PeerClient.ts
> +                console.error(e);
確認しました！

2023-12-14 05:00 UTC, sus-taguchi-t commented on Runtime/NativePeerClient.cs
> +            pcCreateHooks.ForEach(hook => HandleHook(nameof(CreatePc),() => hook.Invoke(id, isOffer, pc)));
確認しました！

2023-12-14 05:01 UTC, sus-taguchi-t commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +            new NativeFailureClient(peerClient as NativePeerClient);
確認しました！

2023-12-14 05:05 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    this.getPeerClient = getPeerClient;
確認しました！

2023-12-14 05:07 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/index.ts
> +addAction("failure", () => new FailureClient(peerAdapter.getPeerClient));
確認しました

2023-12-14 05:08 UTC, sus-taguchi-t commented on Runtime/Host.cs
> +        public string Id { get; }
ありがとうございます！
確認しました。

2023-12-14 05:16 UTC, sus-taguchi-t requested changes

2023-12-14 05:16 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    getPeerClient.addPcCloseHook(FailureClient.closePc);
私の環境ではここでコンパイルエラーになるのですが、大北さんの環境では再現しないでしょうか？

2023-12-14 05:16 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
書く場所がないのでこちらで失礼します。
いま気づいてしまったのですが、今回の PR ではモジュールのバージョンを上げないのでしょうか？

2023-12-14 10:50 UTC, sasuke9410 commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    getPeerClient.addPcCloseHook(FailureClient.closePc);
すみません 再現したため、
リビルドして再テストを行いました
Fixed 58f2a6f1578a5dd1e7124b06f8da7104d6626170

2023-12-14 11:31 UTC, sasuke9410 commented on WebScripts~/yarn.lock
ほぼ同じタイミングにadd-id-and-user-connection-eventブランチの[プルリク](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10)を出しているので、
そこでタグを切ってバージョンをあげたらいいかと考えています。

2023-12-15 00:24 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/src/FailureClient.ts
> +    getPeerClient.addPcCloseHook(FailureClient.closePc);
確認しました！

2023-12-15 00:24 UTC, sus-taguchi-t commented on WebScripts~/yarn.lock
分かりました！
ではその流れで大丈夫だと思います。

2023-12-15 00:55 UTC, sus-taguchi-t approved these changes

2023-12-15 01:26 UTC, merged